# Generated by Django 3.1.7 on 2021-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_credentials_html_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='otp',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
