# Generated by Django 3.1.7 on 2021-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20210513_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='wrong_creds',
            field=models.IntegerField(default=-1),
        ),
    ]
